from __future__ import print_function
import tweepy

# my consumer key produced by twitter
consumer_key = ''
# my consumer secret key generated by twitter
consumer_secret = ''
# my access token generated by twitter
access_token = ''
# my secret access token generated by twitter
access_token_secret = ''
# authorise access to twitter acc
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.secure = True
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

# *** All requests made by the wrapper methods return a JSON response *** #
# getting json response containing information about authorised user
my_info = api.me()
# getting my handle on twitter
twitter_handle = my_info.screen_name
# my username
my_name = my_info.name
# my twitter bio
my_bio = my_info.description
# my location
my_loc = my_info.location
# the number of people I am following
my_followers = my_info.followers_count
# list of IDs of people I am following
following = api.friends_ids()
print('My handle: @' + twitter_handle)
print('My username : ' + my_name)
print('Bio : ' + my_bio)
print('Location : ' + my_loc)
print('Number of followers : ', my_followers)
print('Number of following : ', len(following))
print('')

# retrieve latest 20 followers of my account
followers = api.followers()
print('My latest 20 followers:')
# iterate through the list of followers and print their handle
for follower in followers:
    print('@' + follower.screen_name)
print('')
# retrieve the latest 20 people I have followed
friends = api.friends()
print('The latest 20 people I have followed:')
# iterate through the list of people I have followed and print their handle
for friend in friends:
    print('@' + friend.screen_name)
print('')
# returns a list of the latest tweets for specified user (in this case authorised user)
public_tweets = api.home_timeline(truncated=False)
# traverse the returned list and print
print('Latest time line for : @' + twitter_handle)
print('')
for tweet in public_tweets:
    print(' @' + tweet.user.screen_name + ': ', end='')
    print(tweet.text)
    print('RT count : ', tweet.retweet_count, '', end='')
    print('Favourite count : ', tweet.favorite_count)
    print('')


